- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.4.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.4.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.4.0.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.4.0.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.5.0.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.5.0.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.6.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.6.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.7.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.7.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.7.0.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.7.0.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.7.0.2</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.7.0.2

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.7.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.7.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.8.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.8.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.8.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.8.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.8.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.8.2.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.9.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.9.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.9.0.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.9.0.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.9.0.2</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.9.0.2

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.9.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.9.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.9.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.9.2.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.9.3.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.9.3.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.9.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.9.4.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.9.6.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.9.6.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.9.7.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.9.7.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.9.8.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.9.8.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.9.9.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.9.9.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.9.10.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.9.10.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.10.0.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.10.0.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.10.0.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.10.0.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.10.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.10.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.12.0.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.12.0.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.12.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.12.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.12.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.12.2.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.12.3.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.12.3.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.12.3.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.12.3.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.13.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.13.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.13.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.13.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.13.3.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.13.3.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.14.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.14.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.13.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.13.4.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.14.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.14.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.14.1.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.14.1.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.14.1.2</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.14.1.2

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.14.1.3</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.14.1.3

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.16.3.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.16.3.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.17.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.17.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.17.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.17.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.17.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.17.2.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.17.3.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.17.3.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.17.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.17.4.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.17.6.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.17.6.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.17.7.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.17.7.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.17.8.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.17.8.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.17.9.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.17.9.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.18.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.18.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.19.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.19.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.19.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.19.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.19.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.19.2.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.19.3.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.19.3.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.19.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.19.4.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.20.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.20.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.20.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.20.2.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.21.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.21.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.21.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.21.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.21.1.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.21.1.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.22.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.22.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.23.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.23.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.24.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.24.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.4.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.4.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.4.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.5.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.5.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.5.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.5.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.5.2</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.5.2

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.6.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.6.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.7.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.7.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.8.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.8.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.10.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.10.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.10.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.10.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.11.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.11.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.12.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.12.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.13.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.13.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.14.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.14.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.15.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.15.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.16.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.16.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.16.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.16.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.25.16.2</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.25.16.2

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.27.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.27.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.27.3.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.27.3.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.27.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.27.4.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.28.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.28.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.28.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.28.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.28.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.28.2.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.29.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.29.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.29.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.29.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.30.2.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.30.2.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.30.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.30.4.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.30.6.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.30.6.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.30.7.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.30.7.0

- amazon/core/src/main/kotlin/org/http4k/connect/amazon/profileCredentialsProvider.kt
> Add no-arg constructor to Profile CredentialsProvider

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.30.10.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.30.10.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.34.0.3</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.34.0.3

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.34.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.34.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.35.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.35.4.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.36.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.36.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.41.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.41.4.0

- amazon/sts/client/src/main/kotlin/org/http4k/connect/amazon/sts/profileCredentialsProvider.kt
- amazon/sts/fake/src/test/kotlin/org/http4k/connect/amazon/sts/StsProfileCredentialsProviderTest.kt
> Rename STS CredentialsProvider.Profile to StsProfile

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.47.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 4.47.2.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.1.1.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.1.1.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.1.2.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.1.2.1

- amazon/core/src/main/kotlin/org/http4k/connect/amazon/core/model/ResourceId.kt
- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/model/TableName.kt
Otherwise, I can't extract a `TableName` from an `ARN`
> Make DynamoDb TableName a ResourceId

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.4.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.4.0.0

- amazon/cognito/client/src/main/kotlin/org/http4k/connect/amazon/cognito/action/InitiateAuth.kt
- amazon/cognito/client/src/test/kotlin/org/http4k/connect/amazon/cognito/ActualCognitoResponsesTest.kt
> moshi config was incorrect for successful user password auth reponse 

- amazon/sqs/client/src/main/kotlin/org/http4k/connect/amazon/sqs/action/DeleteMessageBatch.kt
- amazon/sqs/client/src/main/kotlin/org/http4k/connect/amazon/sqs/action/SendMessageBatch.kt
- amazon/sqs/client/src/test/kotlin/org/http4k/connect/amazon/sqs/SQSContract.kt
- amazon/sqs/fake/src/main/kotlin/org/http4k/connect/amazon/sqs/FakeSQS.kt
- amazon/sqs/fake/src/main/kotlin/org/http4k/connect/amazon/sqs/endpoints.kt
- amazon/sqs/fake/src/main/kotlin/org/http4k/connect/amazon/sqs/model.kt
- amazon/sqs/fake/src/main/resources/org/http4k/connect/amazon/sqs/SendMessageBatchResponse.hbs
I should have checked for ALL the operations I needed implemented first🙄
> Add SQS SendMessageBatch action

- README.md
- gradle.properties
- listProjects.sh
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.6.5.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.6.5.0

- amazon/dynamodb/README.md
- amazon/dynamodb/fake/src/examples/kotlin/using_the_table_mapper_simple.kt
Simplifying the readme for the dynamo table mapper.
> Present a more concise introduction to the DynamoDB table mapper

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.8.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.8.4.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.8.5.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.8.5.1

- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbIndexMapper.kt
> Add ConsistentRead to DynamoDbIndexMapper operations

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.10.5.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.10.5.0

- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/model/Attribute.kt
- amazon/dynamodb/client/src/test/kotlin/org/http4k/connect/amazon/dynamodb/model/AttributeTest.kt
Attributes that are optional in DynamoDb tables will become required when used as key in a secondary index. This commit adds a conversion function that turns an optional attribute into a required one, while keeping the name and the data type.
See also https://github.com/http4k/http4k-connect/issues/321
> Add conversion from optional to required Attribute

- amazon/s3/client/src/test/kotlin/org/http4k/connect/amazon/s3/S3BucketContract.kt
- amazon/s3/fake/src/main/kotlin/org/http4k/connect/amazon/s3/endpoints/common.kt
- amazon/s3/fake/src/test/kotlin/org/http4k/connect/amazon/s3/fakeS3Tests.kt
> fake s3 to support bucket requests without host header

- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/query.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/scan.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/DynamoDbQueryContract.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/DynamoDbScanContract.kt
> Fix evaluation order of dynamodb scan/query filter expression

- amazon/cognito/client/src/main/kotlin/org/http4k/connect/amazon/cognito/CognitoMoshi.kt
> Fix Cognito ConfirmationCode and SecretHash not being marshalled as strings

- amazon/dynamodb/README.md
> Amend dynamodb/README with documentation for #329 and #337

- amazon/containercredentials/client/src/main/kotlin/org/http4k/connect/amazon/containercredentials/action/GetCredentials.kt
> Survive AWS container credentials GetCredentialsResponse sometimes having a RoleArn that isn't

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.12.2.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.12.2.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.13.0.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.13.0.1

- amazon/core/src/main/kotlin/org/http4k/connect/amazon/profileCredentialsProvider.kt
- amazon/core/src/test/kotlin/org/http4k/connect/amazon/ProfileCredentialsProviderTest.kt
Fixes https://github.com/http4k/http4k-connect/issues/359
> Simpler API for retrieving the AWS credentials of a custom profile

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.13.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.13.4.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.13.4.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.13.4.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.13.5.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.13.5.0

- amazon/s3/README.md
> Fix endpoint parameter in S3 README

- CHANGELOG.md
- amazon/kms/client/src/main/kotlin/org/http4k/connect/amazon/kms/action/CreateKey.kt
- amazon/kms/client/src/main/kotlin/org/http4k/connect/amazon/kms/action/GetPublicKey.kt
- amazon/kms/client/src/test/kotlin/org/http4k/connect/amazon/kms/KMSContract.kt
- amazon/kms/fake/src/main/kotlin/org/http4k/connect/amazon/kms/endpoints.kt
> Support new KMS KeySpec property

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.13.9.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.13.9.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.14.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.14.0.0

- amazon/dynamodb/client/src/examples/kotlin/using_the_table_mapper.kt
- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbTableMapperSchema.kt
Fixes https://github.com/http4k/http4k-connect/issues/396
> Align secondary index constructors in DynamoDbTableMapperSchema

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.14.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.14.2.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.16.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.16.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.18.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.18.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.18.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.18.2.0

- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/model/StreamsEventResponse.kt
[Slack conversation](https://kotlinlang.slack.com/archives/C5AL3AKUY/p1715360850508939?thread_ts=1715358978.368379&cid=C5AL3AKUY)
[AWS StreamsEventResponse](https://github.com/aws/aws-lambda-java-libs/blob/02d2c061ab38dfede192d43da6624314796ebdad/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/StreamsEventResponse.java#L32)
> Add StreamsEventResponse model

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.21.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.21.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.22.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.22.0.0

- amazon/sqs/fake/src/main/kotlin/org/http4k/connect/amazon/sqs/endpoints.kt
- amazon/sqs/fake/src/test/kotlin/org/http4k/connect/amazon/sqs/AwsSdkV2CompatibilityTest.kt
Fixes compatibility with V2 AWS SDK for Java.
> Fake SendMessageBatch to return null Failed when no failures present

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.24.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.24.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.25.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.25.0.0

- amazon/s3/client/src/main/kotlin/org/http4k/connect/amazon/s3/action/ListObjectsV2.kt
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_ResponseSyntax
> Add `CommonPrefixes` field to S3 `ListObjectsV2` response

- amazon/cognito/client/src/main/kotlin/org/http4k/connect/amazon/cognito/model/cognito.kt
This pull request aims to fix the default  value of the "alg" field in the JWK class
> Update default algorithm value  in JWK cognito.kt

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.27.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.27.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.29.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.29.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.30.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.30.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.30.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.30.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.31.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.31.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.32.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.32.1.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.32.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.32.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.32.3.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.32.3.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.32.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.32.4.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.33.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.33.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.33.0.1</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.33.0.1

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.34.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.34.0.0

- gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.34.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr>
> Auto-upgrade to 5.34.1.0
