- amazon/s3/fake/src/main/kotlin/org/http4k/connect/amazon/s3/endpoints/getKey.kt
- amazon/s3/fake/src/test/kotlin/org/http4k/connect/amazon/s3/fakeS3Tests.kt
Hi!
A problem occurred on encoding when I upgraded http4k-connect from `3.0.2.0` to `3.4.1.0` and I found out it is the `bucketGetKey` method causing this.
To reproduce, you can run the new test `preserve encoding` with the current code. My guess is that when you do the following
```kotlin
String(Base64.getDecoder().decode(it.content))
```
The encoding is lost, because `String` basically works with UTF-8. The solution is to use the `inputStream` instead.
> S3(Fake): preserve encoding in bucketGetKey

- amazon/s3/fake/src/main/kotlin/org/http4k/connect/amazon/s3/endpoints/copyKey.kt
- amazon/s3/fake/src/test/kotlin/org/http4k/connect/amazon/s3/fakeS3Tests.kt
Previously the implementation consistently returned 404's because the source key could not be found in the bucketContent
> Fix FakeS3 to support copying of objects with prefixes

- README.md
These APIs were at the same indentation as the AWS APIs; this will separate them.
> Fix reamde indentation for supported apis

- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/scan.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/DynamoDbSource.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/DynamoDbQueryContract.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/DynamoDbScanContract.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/DynamoDbUpdateItemContract.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/dynamoDbContractHelpers.kt
- Implemented dynamodb `scan` operation, with tests for the fake and local variants
- added local test variant for the `query` operation, as a sanity check against the fake variant
- added local test variant for the `updateItem` operation; fake variant is not yet implemented
> Implement dynamodb fake scan

- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/model/AttributeValue.kt
- amazon/dynamodb/client/src/test/kotlin/org/http4k/connect/amazon/dynamodb/DynamoDbContract.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/helpers.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/updateItem.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/grammar/DynamoDbUpdateExpressionParser.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/DynamoDbSource.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/FakeDynamoDbTest.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/DynamoDbUpdateItemContract.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/grammar/DynamoDbUpdateExpressionParserTest.kt
I didn't do this with `parser4k`, but hopefully my lazy string-manipulation method is good enough for now.  The `DynamoDbContract` can now run in "fake" mode, minus the partiQL operations.
> support updateItem for fake DynamoDb

- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/DynamoTable.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/DynamoDbPutItemContract.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/DynamoDbUpdateItemContract.kt
The fake dynamodb putItem operation will now properly replace an existing item with the same primary key
> Fake DynamoDb PutItem bugfix

- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/model/TableName.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/batchGetItem.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/batchWriteItem.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/FakeDynamoDbTest.kt
- TableName failed to deserialize because it wasn't `Comparable`
- `BatchGetItems` and `BatchWriteItems` responses failed to satisfy the contract because a property was `null` instead of `emptyMap`
> Fix request/response for fake dynamodb batch operations

- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/model/AttributeValue.kt
- amazon/dynamodb/client/src/test/kotlin/org/http4k/connect/amazon/dynamodb/model/AttributeValueTest.kt
The existing `AttributeValue` equality and comparison operators don't work for numeric types, since they currently operate lexicographically.
For Example, these currently evaluate to false:
- `123` > `45` 
- `123` == `123.0`
The equality issue is of particular concern when `Item` is deserialized by moshi; it will always read numbers as double.  This behaviour is known in `AutoMarshalingExtensionsTest.can roundtrip a dynamo item with autoDynamoLens`.  Unfortunately, `BigDecimal.equals` still believes `123` != `123.0`, so we cannot even fix this by making the `N` property into a `BigDecimal`, so must use `BigDecimal.compareTo` to check for effective equality.
> Fix equality and comparison for numeric attribute values

- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/DynamoDbMoshi.kt
- amazon/dynamodb/client/src/test/kotlin/org/http4k/format/AutoMarshalingExtensionsTest.kt
The only way I can add custom mappers (i.e. for values4k classes) is by making a new `ConfigurableMoshi` with a reflective backend.  `kotlinx-metadata` works, but I would rather avoid adding reflection to my lambdas.  It's impossible for me to inject the existing Kotshi factory into a new `ConfigurableMoshi`, because the class is module internal.
This new `update` method will allow me to make a copy of an existing `DynamoDbMoshi`, while providing additional custom marshallers.  For example:
```kotlin
val lens = DynamoDbMoshi.update {
value(CustomValue)
}.autoDynamoLens<MyDbObj>()
```
I see an `update` method like this being very powerful in the built-in `http4k-format` marshallers as well.
> Add ability to update the DynamoDbMoshi marshaller with new config

- amazon/core/src/main/kotlin/org/http4k/connect/amazon/RegionProvider.kt
- amazon/core/src/main/kotlin/org/http4k/connect/amazon/extensions.kt
- amazon/core/src/main/kotlin/org/http4k/connect/amazon/profileRegionProvider.kt
- amazon/core/src/test/kotlin/org/http4k/connect/amazon/EnvironmentRegionProviderTest.kt
- amazon/core/src/test/kotlin/org/http4k/connect/amazon/ProfileRegionProviderTest.kt
- amazon/core/src/test/kotlin/org/http4k/connect/amazon/RegionProviderTest.kt
- amazon/instancemetadata/README.md
- amazon/instancemetadata/client/src/main/kotlin/org/http4k/connect/amazon/instancemetadata/Ec2InstanceProfileRegionProvider.kt
- amazon/instancemetadata/fake/build.gradle.kts
- amazon/instancemetadata/fake/src/examples/kotlin/using_connect_client.kt
- amazon/instancemetadata/fake/src/examples/kotlin/using_credentials_provider.kt
- amazon/instancemetadata/fake/src/examples/kotlin/using_region_provider.kt
- amazon/instancemetadata/fake/src/test/kotlin/org/http4k/connect/amazon/instancemetadata/Ec2InstanceProfileRegionProviderTest.kt
So far, I've decided to leave the client builders untouched.  The region provider can easily calculate the region to be passed in to the existing builder functions.  See the `using_region_provider.kt` example.
> Add Amazon RegionProvider with environment, profile, and imds support

- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/action/Scan.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/DynamoTable.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/helpers.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/query.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/scan.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/DynamoDbQueryContract.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/DynamoDbScanContract.kt
I couldn't _feasibly_ replicate the actual DynamoDB pagination rules (page size of 1 MB), so the fake table has a default limit of 1000 items.  The contract shared by the local and fake implementations is generic enough to ensure page sizes are _roughly_ honoured by both.
For scan, pagination is a little odd, because there's no explicitly defined order for the rows.  Even though the local implementations' ordering seems deterministic, I'm not sure what the algorithm actually is.  So what I've done is have the fake scan apply ordering based on the the index in use, and paginate based on that.  Due to this, the contract will not expect a specific `lastEvaluatedKey` or `items` in each page; it will instead ensure it can use the pagination controls to reach the end.
Closes #232
> Dynamodb query scan pagination

- CHANGELOG.md
- amazon/core/src/main/kotlin/org/http4k/connect/amazon/AmazonJsonFake.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/putItem.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/grammar/AttributeExists.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/grammar/AttributeNotExists.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/DynamoDbPutItemContract.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/grammar/DynamoDbConditionalGrammarTest.kt
Closes #272 
Fake DynamoDB will now support a `ConditionExpression` for `putItem`.
I also discovered a parser bug where `attribute_exists` and `attribute_not_exists` would not accept a name substitution parameter.
> fake dynamodb to support putItem conditions

- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbIndexMapper.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbTableMapperTest.kt
There's a few things happening here, and some of them are breaking:
- The index mapper `query` operation incorrectly exposed a `filter` argument, when it was actually the key condition expression; this has been corrected
- tweaked the index mapper argument casing to be more consistent with the rest of the library; can undo to reduce breaking changes
- Exposed some additional optional arguments to the index mapper
> DynamoDB Index Mapper Argument Tweaks

- amazon/cognito/client/src/main/kotlin/org/http4k/connect/amazon/cognito/action/ConfirmForgotPassword.kt
- amazon/cognito/client/src/main/kotlin/org/http4k/connect/amazon/cognito/model/cognito.kt
Without an update to the fake I'm afraid, as the interactions around AdminResetUserPassword, timeouts etc are just too horrible.
I'm not entirely convinced that the new SecretHash is not the same as the exisiting SecretCode, but I think that they are different.
> Add ConfirmForgotPassword to Cognito

- amazon/core/build.gradle.kts
- amazon/core/src/main/kotlin/org/http4k/connect/amazon/core/model/AwsProfile.kt
- gradle/libs.versions.toml
- versions.properties
Manually parsing the AWS credentials file will allow us to eliminate ini4j.
Technically, I could have used the existing `Environment.fromConfigFile` to parse the ini, but it wouldn't have been returned in a format easy to consume in the way I needed.
> eliminate ini4j

- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/model/itemAndKey.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/helpers.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/query.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/scan.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/DynamoDbQueryContract.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/DynamoDbScanContract.kt
Scan and query operations will no longer return items that don't have the hash or sort key attributes set.
Fixes https://github.com/http4k/http4k-connect/issues/322
> FakeDynamoDb should support sparse indexes

- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbIndexMapper.kt
- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbQueryBuilder.kt
- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/grammar/Contains.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/grammar/DynamoDbConditionalGrammarTest.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbTableMapperTest.kt
This allows creating queries like
```
tableMapper.index(byOwner).query {
keyCondition {
ownerIdAttr eq owner1
}
filterExpression {
val idExpr = idAttr eq kratos.id
val bornExpr = bornAttr gt toggles.born
not(idExpr) and bornExpr
}
}
```
Additional changes:
- adds a queryPage function with full parameters (similar to query())
- fixes the contains(path, operand) function in FakeDynamoDB for string attribute values
Open issues:
- the size function is not supported yet
- the attribute_type function is not supported since it probably doesn't make much sense to support it (attributes are typed and can have only one type)
- comparator functions, BETWEEN, and IN don't allow attributes on their right side yet (something like `attr1 eq attr2`)
See https://github.com/http4k/http4k-connect/issues/314
> Add query builder to DynamoDbIndexMapper query functions

- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/model/Attribute.kt
- amazon/dynamodb/client/src/test/kotlin/org/http4k/connect/amazon/dynamodb/model/AttributeTest.kt
Adds a parameter `ignoreNull` to the `AttrLensSpec.optional()` factory function. Optional attributes with value `null` and `ignoreNull = true` will be missing when sent to DynamoDb. This enables using secondary indexes on optional attributes (aka sparse indexes), since an explicit null value (`{ "NULL": true }`) is not an allowed value for an index key attribute.
See also https://github.com/http4k/http4k-connect/issues/321
> Allow null Attributes to be ignored in the request to DynamoDb

- CHANGELOG.md
- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbTableMapper.kt
The `delete` function in `DynamoDbTableMapper` no longer silently ignores failures returned from DynamoDB.
It now throws the failure the same way all other functions in `DynamoDbTableMapper` are doing it.
> Throw exception if delete fails in DynamoDbTableMapper

- amazon/evidently/client/src/main/kotlin/org/http4k/connect/amazon/evidently/HttpEvidently.kt
I was very confused when I noticed how much logging one of my services was doing.  This was the cause!
> remove debug filter from evidently client

- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/action/Query.kt
- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/action/Scan.kt
- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbIndexMapper.kt
- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbQueryDsl.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbTableMapperTest.kt
Returns the number of items matching the given key condition and/or filter expression.
API changes:
- Scan.Select is now a Select enum (previously String)
- ScanResponse and QueryResponse have now non-optional Count and ScannedCount members (as stated in the AWS API documentation)
> Add count() convenience function to DynamoDbIndexMapper

- openai/client/src/main/kotlin/org/http4k/connect/openai/OpenAIMoshi.kt
- openai/client/src/main/kotlin/org/http4k/connect/openai/action/ChatCompletion.kt
- openai/client/src/main/kotlin/org/http4k/connect/openai/model.kt
- added a constant for `gpt-4-turbo-preview`
- added a constant for the `assistant` role
- added support for [json-mode](https://platform.openai.com/docs/guides/text-generation/json-mode)
> openai: extra constants + json-mode

- amazon/dynamodb/client/src/main/kotlin/org/http4k/format/autoMarshalingExtensions.kt
- amazon/dynamodb/client/src/test/kotlin/org/http4k/format/AutoMarshalingExtensionsTest.kt
I don't think it's possible to support converting java set to dynamo set with the current JSON-backed strategy.  Making a new issue to discuss it.
> Support converting dynamo set to java set

- amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/query.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/DynamoDbQueryContract.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/DynamoDbScanContract.kt
When performing `query` or `scan` on an index, the union of the primary and index key is to be returned as the `lastEvaluatedKey`.  Previously, `query` would only return the index key.
> FakeDynamoDb.query to return proper lastEvaluatedKey for indices

- amazon/dynamodb/README.md
- amazon/dynamodb/client/src/examples/kotlin/using_the_table_mapper.kt
- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbIndexMapper.kt
- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbQueryDsl.kt
- amazon/dynamodb/client/src/test/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbQueryDslTest.kt
- amazon/dynamodb/client/src/test/kotlin/org/http4k/connect/amazon/dynamodb/mapper/queryMatchers.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbTableMapperTest.kt
In the `keyCondition` of a `query` the new values `hashKey` and `sortKey` should be used in place of actual attributes. This makes the DSL more typesafe (it prevents you from using the wrong attributes in the `keyCondition`) and it resolves the problem described in #380
Fixes https://github.com/http4k/http4k-connect/issues/380
> Review DynamoDB query DSL: introduce special values hashKey and sortKey

- CHANGELOG.md
- amazon/dynamodb/client/src/examples/kotlin/using_the_table_mapper.kt
- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbIndexMapper.kt
- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbQueryDsl.kt
- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbTableMapper.kt
- amazon/dynamodb/client/src/main/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbTableMapperSchema.kt
- amazon/dynamodb/client/src/test/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbQueryDslTest.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbTableMapperFixtures.kt
- amazon/dynamodb/fake/src/test/kotlin/org/http4k/connect/amazon/dynamodb/mapper/DynamoDbTableMapperTest.kt
This is a breaking change.  When defining indices, a type argument for the document is now required.
~~I seem to have a heisenbug where when I run all the local dynamo tests, one of them stalls.  But when I run that test class in isolation, it's fine.  I'm going to see if I can reproduce it in the build, or if it's just a local issue.~~  It's just my machine 🙃 
Closes #391
> Dynamodb index mapper custom projections

- amazon/evidently/client/src/main/kotlin/org/http4k/connect/amazon/evidently/model/FeatureName.kt
- amazon/evidently/client/src/main/kotlin/org/http4k/connect/amazon/evidently/model/ProjectName.kt
- amazon/evidently/client/src/test/kotlin/org/http4k/connect/amazon/evidently/model/EvidentlyArnTest.kt
Closes #405 
This isn't perfect, because someone can still do `arn.resourceId(::ProjectName)`.  They have to do `arn.resourceId(ProjectName::parse)` or `ProjectName.of(arn)` due to how the `ARN.resourceId` function works.
> Properly parse evidently project and features names from ARN

- amazon/sqs/client/src/test/kotlin/org/http4k/connect/amazon/sqs/RealSQSTest.kt
- amazon/sqs/client/src/test/kotlin/org/http4k/connect/amazon/sqs/SQSContract.kt
It wasn't possible to apply the retry at the HTTP level since the not-yet-consistent responses have successful status codes.
Instead, I created a retry mechanism to wrap the test logic.  The fake tests have zero tolerance for failure, but the real test will wait for up to a minute to wait for the data to become consistent.
> Deflake RealSQSTest

- amazon/s3/client/src/main/kotlin/org/http4k/connect/amazon/s3/action/CreateBucket.kt
- amazon/s3/client/src/test/kotlin/org/http4k/connect/amazon/s3/S3GlobalContract.kt
This is really dumb, but if you give a location constraint for the default (us-east-1) S3 region, the request fails.  And if you put an empty `CreateBucketConfiguration` element, the request fails.  So an XML body is only added if the region is non-default.
> Fix s3:createBucket request body for default (us-east-1) region

- amazon/sqs/client/src/main/kotlin/org/http4k/connect/amazon/sqs/action/ReceiveMessage.kt
- amazon/sqs/client/src/test/kotlin/org/http4k/connect/amazon/sqs/SQSContract.kt
- amazon/sqs/fake/src/test/kotlin/org/http4k/connect/amazon/sqs/FakeSQSTest.kt
This is a breaking change.  If we wish for it to not be breaking, there are overrides I can perform to make it so.
> Fix type of SQS ReceiveMessage waitTimeSeconds parameter

- amazon/cognito/client/src/main/kotlin/org/http4k/connect/amazon/cognito/CognitoMoshi.kt
- amazon/cognito/client/src/main/kotlin/org/http4k/connect/amazon/cognito/action/AdminInitiateAuth.kt
- amazon/cognito/client/src/main/kotlin/org/http4k/connect/amazon/cognito/action/AdminRespondToAuthChallenge.kt
- amazon/cognito/client/src/main/kotlin/org/http4k/connect/amazon/cognito/action/InitiateAuth.kt
- amazon/cognito/client/src/main/kotlin/org/http4k/connect/amazon/cognito/model/cognito.kt
- amazon/cognito/client/src/test/kotlin/org/http4k/connect/amazon/cognito/ActualCognitoResponsesTest.kt
Support the server-side authentication flow with AdminInitiateAuth and AdminRespondToAuthChallenge.
> AWS Cognito: Add support for server side authentication (AdminInitiateAuth and AdminRespondToAuthChallenge)
